"""List of 1000+ public Telegram channel usernames for parsing."""

CHANNELS: list[str] = [
    # ── Новости России ────────────────────────────────────────────────────────
    "rbc_news",
    "rian_ru",
    "tass_agency",
    "kommersant",
    "vedomosti",
    "fontanka_spb",
    "mediazzzona",
    "novayagazeta",
    "bbcrussian",
    "rtvinews",
    "rtnews",
    "interfax_russia",
    "izvestia",
    "ng_ru",
    "mk_ru",
    "aif_ru",
    "gazeta_ru",
    "lenta_ru",
    "meduza_io",
    "tvrain",
    "moskovskij_komsomolets",
    "rus_life",
    "shot_shot",
    "ria_novosti",
    "mash",
    "baza_io",
    "readovkanews",
    "dva_majors",
    "kremlinrussia",
    "sovfed",
    "russia_24",
    "1tv_russia",
    "nbcnewsru",
    "lifenews_ru",
    "rusnewstoday",
    "kpru",
    "regnum_news",
    "bloknot_ru",
    "novye_izvestia",
    "the_ins_insider",
    "octagonmedia",
    "agendarussia",
    "russica_ru",
    "newsru_ua",
    "russian_field",
    "pzdcnews",
    "radiosvoboda",
    "svoboda_media",
    "currenttime_tv",
    "smi2ru",

    # ── Регионы России ────────────────────────────────────────────────────────
    "kuban24tv",
    "e1_ru",
    "eburg_news",
    "nsk_express",
    "kras24_tv",
    "taygamedia",
    "76_ru",
    "ngs_ru",
    "74ru",
    "primamedia",
    "sakhalin_news",
    "yakutsk_online",
    "irkutsk_news",
    "tomsk_online",
    "omsk_city",
    "ufa_news",
    "kazan_ru",
    "tatarstan_news",
    "samara_news_ru",
    "nn_ru",
    "perm_ru",
    "voronezh_ru",
    "rostov_ru",
    "volgograd_ru",
    "krasnodar_ru",
    "spb_tv",
    "spb_news",
    "piter_online",
    "nevnov",
    "mr7_spb",

    # ── Украина / СНГ ─────────────────────────────────────────────────────────
    "ukraina_news",
    "ukrinform_ua",
    "unian_ua",
    "pravda_ua",
    "hromadske",
    "zn_ua",
    "liga_net",
    "suspilnemedia",
    "bbc_ukraine",
    "radio_svoboda_ua",
    "kyiv_independent",
    "the_new_voice_of_ukraine",
    "kyivpost",
    "insiderua",
    "obozrevatel",
    "strana_ukraine",
    "belarusian_news",
    "tutby",
    "onliner_by",
    "nn_by",
    "zerkalo_io",
    "nashaniva",
    "zaboraby",
    "nexta_tv",
    "nextalive",
    "kazakh_news",
    "tengrinews",
    "informburo_kz",
    "kz_news",
    "uzbekistan_news",
    "kun_uz",

    # ── Международные новости ─────────────────────────────────────────────────
    "reuters",
    "bbcnews",
    "cnn",
    "nytimes",
    "guardian",
    "aljazeera",
    "dw_russian",
    "deutschewelle",
    "france24",
    "euronews",
    "ap_news",
    "bbc_world_service",
    "the_economist",
    "ft_news",
    "bloomberg_markets",
    "wsj_news",
    "abcnews",
    "nbcnews",
    "cbsnews",
    "foxnewsalerts",
    "politico",
    "thehill",
    "vox",
    "axios",
    "theatlantic",
    "newyorker",
    "time_magazine",
    "newsweek",
    "independent_uk",
    "telegraph_uk",

    # ── Политика ──────────────────────────────────────────────────────────────
    "politota_ru",
    "politolog_orlov",
    "russica_ru",
    "karaulny",
    "kremlinrussia_channel",
    "dimsmirnov",
    "solovievlive",
    "margaritasimonyan",
    "kiselyov_tg",
    "polit_insider",
    "polit_russia",
    "rasstriga",
    "proekt_media",
    "belkovskiy",
    "politnavigator",
    "gordonua",
    "general_svr",
    "legitimniy",
    "warmonitor",
    "grey_zone",
    "rybar",
    "wargonzo",
    "SolovievLive",
    "vladimirputin",
    "dpmitonov",
    "newsland_ru",
    "tgrussia",
    "tgukraine",
    "ukraina_bazar",
    "antifascistua",

    # ── Экономика и финансы ───────────────────────────────────────────────────
    "cbr_official",
    "moexru",
    "investfuture",
    "fomchannel",
    "cbrstocks",
    "smartlab_official",
    "finam_ru",
    "rbc_investments",
    "olegmakarenko",
    "markettwits",
    "truevalue",
    "AK47pfl",
    "mfd_ru",
    "tinkoff_invest",
    "sber_official",
    "alfa_official",
    "vtb_official",
    "open_broker",
    "bcs_express",
    "investingru",
    "economics_ru",
    "macro_markets",
    "profinance_ru",
    "bloomberg_economics",
    "economist_russia",
    "cbonds_news",
    "forex_official",
    "cryptogrief",
    "cryptopanic",
    "cointelegraph",

    # ── Технологии ────────────────────────────────────────────────────────────
    "habr",
    "tjournal",
    "vc_ru",
    "it_ru",
    "proglib",
    "pythonru",
    "devops_chat",
    "kubernetes_io",
    "linuxru",
    "codingit",
    "dataleak",
    "cybersecurity_news",
    "security_ru",
    "pentestit",
    "hackernews_ru",
    "geekbrains",
    "skillbox_news",
    "yandex_blog",
    "mail_tech",
    "vk_official",
    "sber_tech",
    "tinkoff_tech",
    "kaspersky",
    "drweb",
    "infosecurity_ru",
    "techcabal",
    "techcrunch",
    "theverge",
    "wired_news",
    "engadget",
    "arstechnica",
    "mit_tech_review",
    "ieee_spectrum",
    "slashdot",
    "producthunt",

    # ── AI / ML ───────────────────────────────────────────────────────────────
    "openai_official",
    "anthropic_ai",
    "deepmind",
    "ai_ru",
    "machinelearning_ru",
    "datascience_ru",
    "pytorch_official",
    "tensorflow_official",
    "huggingface",
    "airesearch",
    "nlp_news",
    "paperswithcode",
    "gradio_official",
    "langchain_ai",
    "llm_news",
    "agi_news",
    "mlops_community",
    "kaggle",
    "data_engineering_ru",
    "analyticsvidhya",

    # ── Программирование ──────────────────────────────────────────────────────
    "python_coding",
    "python3_ru",
    "golang_news",
    "rust_lang",
    "javascript_news",
    "typescript_news",
    "reactjs_news",
    "vuejs_news",
    "nodejs_official",
    "flutter_dev",
    "android_dev_ru",
    "ios_dev_ru",
    "swift_lang",
    "kotlinlang",
    "java_news",
    "spring_boot_news",
    "dotnet_news",
    "csharp_ru",
    "cpp_ru",
    "ruby_news",
    "php_news",
    "scala_news",
    "haskell_news",
    "database_news",
    "postgresql_news",
    "mysql_news",
    "mongodb_news",
    "redis_news",
    "elasticsearch_news",
    "graphql_news",

    # ── DevOps / Cloud ────────────────────────────────────────────────────────
    "devops_ru",
    "sre_news",
    "terraform_news",
    "ansible_news",
    "docker_news",
    "k8s_news",
    "aws_official",
    "azure_official",
    "googlecloud",
    "yandex_cloud",
    "sber_cloud",
    "cloud_news_ru",
    "ci_cd_news",
    "jenkins_news",
    "gitlab_official",
    "github_official",
    "linux_kernel",
    "openstack_news",
    "prometheus_official",
    "grafana_official",

    # ── Кибербезопасность ─────────────────────────────────────────────────────
    "sec_news_ru",
    "hackers_news",
    "vulnerabilities_ru",
    "cve_news",
    "zeroday_news",
    "pentesting_ru",
    "osint_ru",
    "infosec_ru",
    "darkweb_news",
    "malware_news",
    "phishing_news",
    "cryptography_news",
    "bugbounty_ru",
    "redteam_news",
    "blueblue_team",

    # ── Криптовалюты ──────────────────────────────────────────────────────────
    "bitcoin_news",
    "ethereum_news",
    "crypto_ru",
    "crypto_analytics",
    "defi_news",
    "nft_news",
    "binance_official",
    "coinbase_official",
    "bybit_official",
    "kraken_official",
    "huobi_official",
    "okx_official",
    "kucoin_official",
    "gate_io",
    "pancakeswap",
    "uniswap",
    "aave_official",
    "compound_official",
    "chainlink_news",
    "polkadot_news",
    "solana_news",
    "avalanche_official",
    "near_protocol",
    "cosmos_news",
    "cardano_official",
    "ripple_official",
    "litecoin_official",
    "dogecoin_official",
    "shiba_inu_official",

    # ── Наука и образование ───────────────────────────────────────────────────
    "scienceru",
    "nauka_ru",
    "roscosmos",
    "cern_official",
    "nasa_official",
    "eso_official",
    "nature_journal",
    "science_magazine",
    "newscientist",
    "physics_news",
    "chemistry_news",
    "biology_news",
    "medicine_news",
    "psychology_news",
    "sociology_news",
    "history_ru",
    "geography_ru",
    "linguistics_ru",
    "mathematics_ru",
    "philosophy_ru",
    "education_ru",
    "schools_ru",
    "universities_ru",
    "coursera_official",
    "edx_official",
    "stepik_official",
    "skillfactory",
    "netology_ru",

    # ── Здоровье и медицина ───────────────────────────────────────────────────
    "medportal_ru",
    "health_ru",
    "koronavirus_ru",
    "who_official",
    "covid19_ru",
    "vaccine_news",
    "pharmacy_ru",
    "doctor_online",
    "nutrition_ru",
    "fitness_ru",
    "yoga_ru",
    "mental_health_ru",
    "psychotherapy_ru",

    # ── Спорт ─────────────────────────────────────────────────────────────────
    "sport_ru",
    "sport24_ru",
    "rsport_news",
    "championat",
    "euro_football",
    "premierleague_official",
    "uefa_official",
    "fifa_official",
    "bundesliga_official",
    "seriea_official",
    "laliga_official",
    "mls_official",
    "nba_official",
    "nfl_official",
    "nhl_official",
    "mlb_official",
    "formula1_official",
    "motogp_official",
    "tennis_atp",
    "tennis_wta",
    "olympic_official",
    "cska_official",
    "spartak_official",
    "zenit_official",
    "lokomotiv_official",
    "dynamo_ru",
    "real_madrid",
    "barcelona_fc",
    "manchester_united",
    "liverpool_fc",
    "chelsea_fc",
    "arsenal_fc",
    "manchester_city",
    "psg_official",
    "juventus_official",
    "milan_official",
    "inter_official",

    # ── Авто ──────────────────────────────────────────────────────────────────
    "auto_ru",
    "drive2_official",
    "autoreview_ru",
    "zr_ru",
    "carbuzz",
    "motortrend",
    "caranddriver",
    "roadandtrack",
    "topgear_official",
    "jalopnik",
    "tesla_official",
    "bmw_official",
    "mercedes_official",
    "audi_official",
    "volkswagen_official",
    "toyota_official",
    "honda_official",
    "ford_official",
    "gm_official",
    "lada_official",

    # ── Недвижимость ──────────────────────────────────────────────────────────
    "realty_ru",
    "cian_official",
    "avito_realty",
    "domclick",
    "yandex_realty",
    "pik_official",
    "lst_official",
    "samolet_official",
    "etalon_official",

    # ── Бизнес и предпринимательство ─────────────────────────────────────────
    "business_ru",
    "forbes_russia",
    "inc_russia",
    "entrepreneur_ru",
    "startup_ru",
    "vc_startup",
    "rusbase",
    "rb_ru",
    "gkh_ru",
    "tinkoff_business",
    "sberbusiness",
    "hh_official",
    "headhunter",
    "superjob_official",
    "zarplata_ru",
    "rabota_ru",
    "e_xecutive",
    "management_ru",
    "marketing_ru",
    "pr_ru",

    # ── Культура и искусство ──────────────────────────────────────────────────
    "culture_ru",
    "art_ru",
    "museum_official",
    "hermitage_official",
    "tretyakov_gallery",
    "bolshoi_official",
    "mariinsky_official",
    "pushkin_museum",
    "artforum",
    "artnet_news",
    "frieze_art",
    "designboom",
    "dezeen",
    "wallpaper_mag",
    "blueprint_ru",
    "afisha_ru",

    # ── Кино и сериалы ────────────────────────────────────────────────────────
    "kinopoisk_official",
    "imdb_official",
    "rottentomatoes",
    "film_ru",
    "kinoblog",
    "movie_news",
    "serialmania",
    "netflix_official",
    "hbo_official",
    "amazon_prime",
    "disney_plus",
    "apple_tv",
    "paramount_plus",
    "peacock_tv",
    "hulu_official",
    "criterion_collection",
    "a24films",

    # ── Музыка ────────────────────────────────────────────────────────────────
    "music_ru",
    "musicnews_ru",
    "pitchfork",
    "nme_music",
    "rollingstone_music",
    "billboardnews",
    "stereogum",
    "consequence_sound",
    "genius_official",
    "spotify_official",
    "apple_music",
    "yandex_music",
    "vk_music",
    "zvuk_official",

    # ── Книги и литература ────────────────────────────────────────────────────
    "knigi_ru",
    "litres_official",
    "bookmate_official",
    "chitai_gorod",
    "labirint_books",
    "eksmo_official",
    "ast_official",
    "corpus_books",
    "nlobooks",
    "phantastic_ru",
    "fantlab_ru",
    "livelib_official",
    "goodreads_official",
    "ny_times_books",
    "guardian_books",

    # ── Игры ──────────────────────────────────────────────────────────────────
    "games_ru",
    "stopgame_ru",
    "dtf_games",
    "igromania_official",
    "gamespot",
    "ign_games",
    "kotaku",
    "polygon_games",
    "eurogamer",
    "steam_official",
    "epicgames_official",
    "gog_official",
    "blizzard_official",
    "ea_official",
    "ubisoft_official",
    "activision",
    "2k_games",
    "bethesda_official",
    "cdprojektred",
    "valve_official",
    "riot_games",
    "roblox_official",
    "minecraft_official",
    "fortnite_official",
    "gta_official",

    # ── Путешествия и туризм ──────────────────────────────────────────────────
    "travel_ru",
    "tourprom_ru",
    "tutu_ru",
    "aviasales_official",
    "skyscanner",
    "booking_official",
    "airbnb_official",
    "tripadvisor_official",
    "lonelyplanet",
    "natgeotravel",
    "travelandleisure",
    "cntraveler",
    "afar_media",
    "travoice",

    # ── Еда и кулинария ───────────────────────────────────────────────────────
    "eda_ru",
    "gastronom_ru",
    "bon_appetit",
    "serious_eats",
    "food52",
    "tasty_official",
    "eater",
    "bloomberg_food",
    "saveur_magazine",
    "epicurious",
    "yandex_eda",
    "delivery_club",
    "sber_market",

    # ── Мода и красота ────────────────────────────────────────────────────────
    "fashion_ru",
    "vogue_russia",
    "elle_russia",
    "gq_russia",
    "cosmo_russia",
    "instyle_russia",
    "bazaar_russia",
    "allure_official",
    "wwd_fashion",
    "bof_fashion",
    "hypebeast",
    "streetwear_news",
    "sneakers_ru",
    "lamoda_official",
    "wildberries_official",
    "ozon_fashion",

    # ── Лайфстайл ─────────────────────────────────────────────────────────────
    "lifestyle_ru",
    "the_village",
    "bbc_lifestyle",
    "gq_lifestyle",
    "mens_health",
    "womens_health_ru",
    "esquire_russia",
    "maxim_russia",
    "playboy_ru",
    "thrillist",

    # ── Юмор / Мемы ───────────────────────────────────────────────────────────
    "humor_ru",
    "anekdoty_ru",
    "pikabu_official",
    "typical_ru",
    "typical_programmer",
    "ithink_ru",
    "meme_ru",
    "lurk_ru",
    "awkward_ru",

    # ── Психология и саморазвитие ─────────────────────────────────────────────
    "psy_ru",
    "psychology_today",
    "lifehacker_ru",
    "productivity_ru",
    "habits_ru",
    "mindfulness_ru",
    "stoicism_ru",
    "mental_ru",
    "therapy_ru",
    "coaching_ru",

    # ── Экология и природа ────────────────────────────────────────────────────
    "ecology_ru",
    "greenpeace_russia",
    "wwf_russia",
    "nature_news",
    "national_geographic",
    "bbc_earth",
    "climate_news",
    "renewableenergy",
    "solar_energy_news",
    "wind_energy_news",
    "nuclear_news",

    # ── Право и юриспруденция ─────────────────────────────────────────────────
    "pravo_ru",
    "law_ru",
    "yurist_online",
    "consultant_plus",
    "garant_official",
    "verkhovny_sud",
    "arbitr_news",
    "legal_news",
    "taxes_ru",
    "nalog_official",

    # ── Государство и власть ──────────────────────────────────────────────────
    "kremlin_official",
    "government_ru",
    "gosdumaofficial",
    "sfr_official",
    "minfinru",
    "mincultru",
    "mintransru",
    "minobrnauki",
    "minzdrav_official",
    "rosstat_official",
    "fns_official",
    "fsb_official",
    "mvd_russia",
    "roskomnadzor",
    "rostelecom",

    # ── Религия и философия ───────────────────────────────────────────────────
    "rpc_official",
    "patriarh_official",
    "islam_news",
    "buddhism_ru",
    "judaism_ru",
    "protestant_ru",
    "philosophy_ru_ch",
    "ethics_ru",
    "theology_ru",

    # ── Военная тематика ──────────────────────────────────────────────────────
    "mil_ru",
    "zvezda_official",
    "nvo_ru",
    "vpk_news",
    "flot_news",
    "avia_news_ru",
    "tank_news",
    "army_news",
    "nato_official",

    # ── Астрономия и космос ───────────────────────────────────────────────────
    "kosmos_ru",
    "roscosmos_official",
    "spacex_official",
    "nasa_feed",
    "esa_official",
    "jaxa_official",
    "isro_official",
    "spacenews",
    "astronomy_ru",
    "hubble_official",
    "jwst_news",

    # ── Животные и зоология ───────────────────────────────────────────────────
    "animals_ru",
    "cats_ru",
    "dogs_ru",
    "wildlife_news",
    "pets_official",
    "zoo_moscow",
    "zoo_spb",
    "animalnews",

    # ── Транспорт и логистика ─────────────────────────────────────────────────
    "transport_ru",
    "rzdofficial",
    "aeroflot_official",
    "s7airlines",
    "utair_official",
    "pobeda_airlines",
    "shipping_news",
    "logistics_ru",

    # ── Энергетика ────────────────────────────────────────────────────────────
    "gazprom_official",
    "rosneft_official",
    "lukoil_official",
    "novatek_official",
    "transneft_official",
    "rosatom_official",
    "rushydro_official",
    "inter_rao",
    "energy_news_ru",

    # ── Ритейл и e-commerce ───────────────────────────────────────────────────
    "ozon_official",
    "wildberries_news",
    "magnit_official",
    "xfive_official",
    "lenta_shop",
    "auchan_official",
    "metro_official",
    "mvideo_official",
    "eldorado_official",
    "dns_official",
    "citilink_official",
    "alibaba_official",
    "amazon_official",
    "ebay_official",
    "jd_official",
    "aliexpress_ru",

    # ── HR и карьера ──────────────────────────────────────────────────────────
    "hr_ru",
    "hh_ru",
    "superjob_news",
    "career_ru",
    "zarplata_official",
    "glassdoor",
    "linkedin_official",
    "indeed_official",
    "remote_work",
    "freelance_ru",

    # ── Продуктивность и инструменты ─────────────────────────────────────────
    "notion_official",
    "obsidian_md",
    "roamresearch",
    "evernote_official",
    "todoist_official",
    "trello_official",
    "jira_official",
    "confluence_official",
    "slack_official",
    "zoom_official",
    "microsoft_teams",
    "google_workspace",

    # ── Социальные сети и медиа ───────────────────────────────────────────────
    "vk_official_news",
    "odnoklassniki",
    "telegram_official",
    "twitter_official",
    "instagram_official",
    "facebook_official",
    "tiktok_official",
    "youtube_official",
    "twitch_official",
    "discord_official",
    "reddit_official",
    "medium_official",
    "substack_news",

    # ── Благотворительность ───────────────────────────────────────────────────
    "charity_ru",
    "unicef_official",
    "redcross_official",
    "amnesty_official",
    "hrw_official",
    "oxfam_official",
    "msf_official",
    "savethechildren",
    "wikimedia_official",

    # ── Разное / Интересное ───────────────────────────────────────────────────
    "interesting_facts",
    "did_you_know_ru",
    "wondershare",
    "vsauce_official",
    "ted_talks",
    "brain_pickings",
    "mental_floss",
    "quora_official",
    "wikipedia_official",
    "britannica_official",

    # ── Дополнительные новостные каналы ──────────────────────────────────────
    "tgrussia2",
    "smi60",
    "politota2",
    "meduzaio",
    "theinsider",
    "nv_ua",
    "dsnews_ua",
    "lb_ua",
    "ukr_pravda_eng",
    "censor_net",
    "militarnyi",
    "suspilne_news",
    "radiosvobodaua",
    "golos_ameriki",
    "bbc_russia",
    "vedomosti2",
    "kommersant2",
    "znak_com",
    "zona_media",
    "ovd_info",
    "bumaga_media",
    "paperjournalru",
    "severreal",
    "kavkazuzel",
    "thebarentsobserver",

    # ── Дополнительные технологии ─────────────────────────────────────────────
    "ai_daily_news",
    "neural_network_news",
    "gpt4_news",
    "chatgpt_official",
    "bard_official",
    "copilot_news",
    "stable_diffusion",
    "midjourney_official",
    "dalle_news",
    "generative_ai_news",
    "llm_benchmarks",
    "rlhf_news",
    "vector_db_news",
    "pinecone_official",
    "weaviate_official",
    "chroma_db",
    "qdrant_official",
    "milvus_official",
    "faiss_news",
    "annoy_news",

    # ── Дополнительные финансы ─────────────────────────────────────────────────
    "finmarket_ru",
    "forex_club",
    "trade_signals",
    "etf_news",
    "stock_market_ru",
    "bonds_ru",
    "commodities_ru",
    "futures_news",
    "options_news",
    "derivatives_ru",
    "hedge_funds_news",
    "venture_capital",
    "private_equity",
    "ipo_news",
    "m_and_a_news",
    "economic_calendar",
    "macro_news",
    "fed_news",
    "ecb_news",
    "boe_news",

    # ── Дополнительный спорт ───────────────────────────────────────────────────
    "boxing_news",
    "mma_news",
    "ufc_official",
    "wrestling_news",
    "cycling_news",
    "athletics_news",
    "swimming_news",
    "gymnastics_news",
    "weightlifting_news",
    "rowing_news",
    "sailing_news",
    "golf_official",
    "polo_news",
    "rugby_news",
    "cricket_official",
    "baseball_official",
    "volleyball_news",
    "basketball_ru",
    "ice_hockey_ru",
    "biathlon_ru",
    "skiing_news",
    "snowboard_news",
    "figure_skating",
    "speed_skating",

    # ── Дополнительные игры ────────────────────────────────────────────────────
    "cybersport_ru",
    "esports_news",
    "dota2_official",
    "cs2_official",
    "valorant_official",
    "overwatch_official",
    "hearthstone",
    "legend_of_zelda",
    "super_mario",
    "pokemon_official",
    "final_fantasy",
    "dark_souls_news",
    "elden_ring",
    "hollow_knight",
    "indie_games",
    "retro_games",
    "game_dev_news",
    "unity_official",
    "unreal_engine",
    "godot_engine",

    # ── Дополнительная наука ───────────────────────────────────────────────────
    "quantum_computing",
    "neuroscience_news",
    "genetics_news",
    "genomics_news",
    "biotech_news",
    "nanotech_news",
    "material_science",
    "robotics_news",
    "autonomous_vehicles",
    "drone_news",
    "3d_printing",
    "vr_ar_news",
    "metaverse_news",
    "iot_news",
    "blockchain_tech",
    "web3_news",
    "decentralized_finance",
    "smart_contracts",
    "dao_news",
    "tokenomics",

    # ── Дополнительная медицина ────────────────────────────────────────────────
    "oncology_news",
    "cardiology_news",
    "neurology_news",
    "psychiatry_news",
    "pediatrics_news",
    "surgery_news",
    "pharmacology_news",
    "clinical_trials",
    "genetics_medicine",
    "immunology_news",
    "virology_news",
    "bacteriology_news",
    "epidemiology_news",
    "public_health_news",
    "telemedicine_news",

    # ── Архитектура и дизайн ──────────────────────────────────────────────────
    "architecture_ru",
    "design_ru",
    "interior_design",
    "urban_planning",
    "landscape_design",
    "graphic_design",
    "ux_design",
    "ui_design",
    "product_design",
    "industrial_design",
    "fashion_design",
    "typography_news",
    "color_theory",
    "design_trends",
    "behance_official",
    "dribbble_official",
    "awwwards_official",

    # ── Фотография ────────────────────────────────────────────────────────────
    "photography_ru",
    "photo_news",
    "natgeo_photo",
    "magnum_photos",
    "world_press_photo",
    "flickr_official",
    "500px_official",
    "instagram_photo",
    "photojournalism",
    "portrait_photo",
    "landscape_photo",
    "street_photo",
    "wildlife_photo",

    # ── Журналистика и медиа ──────────────────────────────────────────────────
    "journalism_ru",
    "media_news",
    "cpj_official",
    "rsf_official",
    "ifj_official",
    "spj_official",
    "poynter_institute",
    "niemanlab",
    "columbia_journalism",
    "pressgazette",
    "mediashift",
    "journalism_awards",

    # ── Региональные международные ────────────────────────────────────────────
    "china_news",
    "xinhua_official",
    "cgtn_official",
    "people_daily",
    "scmp_official",
    "japan_news",
    "nhk_official",
    "asahi_shimbun",
    "nikkei_asia",
    "india_news",
    "hindustan_times",
    "times_of_india",
    "ndtv_official",
    "middle_east_news",
    "al_arabiya",
    "africa_news",
    "latin_america_news",
    "telesur_official",

    # ── Остальные разные каналы ────────────────────────────────────────────────
    "worldnews_daily",
    "breakingnews",
    "global_news",
    "morning_briefing",
    "evening_news",
    "weekly_digest",
    "fact_check_news",
    "debunking_myths",
    "conspiracy_theories",
    "alternative_media",
    "citizen_journalism",
    "data_journalism",
    "investigative_news",
    "exclusive_news",
    "leak_news",
    "whistle_blowers",
    "anonymous_news",
    "underground_news",
    "counterculture_ru",
    "subculture_news",
]
